---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint
    image: mhart/alpine-node:14
    commands:
      - npm ci
      - npm run lint
  - name: tag
    image: busybox
    commands:
      - echo "${DRONE_BRANCH//\//-}"
      - echo "${DRONE_BRANCH/\//-}"
      - echo -n "${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}" > .tags
      - if [ ${DRONE_BRANCH} = "master" ]; then echo -n ',stable,latest' >> .tags; else echo -n ',dev' >> .tags; fi
    depends_on:
      - lint
  # - name: build
  #   image: plugins/docker
  #   settings:
  #     registry: cr.ablab.io
  #     repo: cr.ablab.io/oxeye
  #     username:
  #       from_secret: registry_username
  #     password:
  #       from_secret: registry_password
  #   depends_on:
  #     - tag
