---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint
    image: node:12
    commands:
      - npm ci
      - npm run lint
    volumes:
      - name: node-modules-cache
        path: /drone/src/node_modules
  - name: tag
    image: busybox
    commands:
      - echo -n "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}" > .tags
      - if [ ${DRONE_BRANCH} = "master" ]; then echo -n ',stable,latest' >> .tags; else echo -n ',dev' >> .tags; fi
    depends_on:
      - lint
  - name: build
    image: plugins/docker
    settings:
      registry: cr.ablab.io
      repo: oxeye
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      cache_from: cr.ablab.io/oxeye
    volumes:
      - name: node-modules-cache
        path: /drone/src/node_modules
    depends_on:
      - tag
  # - name: deploy
  #   image: quay.io/honestbee/drone-kubernetes
  #   settings:
  #     kubernetes_server:
  #       from_secret: deploy_server
  #     kubernetes_cert:
  #       from_secret: deploy_cert
  #     kubernetes_token:
  #       from_secret: deploy_token
  #     repo: cr.ablab.io/oxeye
  #     tag: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
  #     deployment: oxeye
  #     container: oxeye
  #   depends_on:
  #     - build
  #   when:
  #     branch:
  #       - master
  #     event:
  #       - push

volumes:
  - name: node-modules-cache
    host:
      path: /tmp/cache/${DRONE_REPO}/node-modules
