version: "3.7"

services:
  mongo:
    image: mongo:4
    container_name: oxeye-mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=oxeye
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo:/data/db
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    container_name: oxeye-mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    ports:
      - 3001:8081
    logging:
      driver: none
  oxeye:
    build:
      context: .
      dockerfile: dev/Dockerfile
      args:
        - UID
        - GID
    container_name: oxeye
    depends_on:
      - mongo
    restart: always
    environment:
      - MONGO_URI
      - JWT_SECRET_KEY
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 10000:10000
volumes:
  mongo:
